/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bookRepository;

import java.io.FileNotFoundException;
import java.io.UnsupportedEncodingException;
import java.sql.SQLException;

public interface bookRepositoryInterface {

    void saveInOracle(Book book) throws ClassNotFoundException, SQLException;

    void saveInFile(Book book, String file) throws FileNotFoundException, UnsupportedEncodingException;
}
