/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bookRepository;

import org.junit.Assert;
import org.junit.Test;
import static org.junit.Assert.*;

public class BookFSRepositoryTest {

    private BookFSRepository repository = new BookFSRepository("./books");

    @Test
    public void testSave() {
        repository.save(new Book("LOTR", "Tolkein", 1000));
    }

    @Test
    public void testNullSave() {
        repository.save(null);
    }
}
